sudo: false
language: node_js
node_js:
  - "10"
before_install:
  - curl -sSL https://get.rvm.io | bash -s stable --ruby
  - gem install compass
  - npm install -g grunt-cli yarn
install:
  - yarn
before_script:
  - 'grunt build'
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: teemops-ui.zip
  skip_cleanup: true
  on:
    tags: true