sudo: false
language: node_js
node_js:
  - "10"
before_install:
  - gem install compass
  - npm install -g grunt-cli bower
install:
  - npm install
  - bower install
before_script:
  - 'grunt build'
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: teemops-ui.zip
  skip_cleanup: true
  on:
    tags: true