sudo: false
language: node_js
node_js:
  - "10"
before_script:
  - 'npm install -g bower grunt-cli'
  # - 'bower install'
install:
  - grunt build
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: teemops-ui.zip
  skip_cleanup: true
  on:
    tags: true