sudo: false
language: node_js
node_js:
  - "10"
before_install:
  - gem install compass
  - npm install -g grunt-cli yarn
install:
  - yarn
before_script:
  - 'grunt build'
before_deploy: cd dist && zip -r ../teemops-ui.zip . && cd ../
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: teemops-ui.zip
  skip_cleanup: true
  on:
    tags: true