sudo: false
language: node_js
node_js:
  - "12"
before_install: 
  - npm install -g grunt-cli
  - bower install
install:
  - npm install
before_script:
  - 'grunt build'
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: teemops-ui.zip
  skip_cleanup: true
  on:
    tags: true